print("I'm going to inject %s here." %'something')
print("I'm going to inject %s text here, and %s text here." %('some','more'))
x,y = 'some', 'more'
print("I'm going to inject %s text here, and %s text here." %(x,y))
print('he said his name was %s.' %'fred')
print('he said his name was %r.' %'fred')
print('I once caught a fish %s.' %'this \tbig')
print('I once caught a fish %r.' %'this \tbig')
print('I wrote %s programs today.' %3.75)
print('I wrote %d programs today.' %3.75)
print('floating point numbers: %5.2f' %(13.144))
print('floating point numbers: %1.0f' %(13.144))
print('floating point numbers: %1.5f' %(13.144))
print('floatinf point numbers: %10.2f' %(13.144))
print('floating point numbers: %25.2f' %(13.144))
print('first: %s, second: %5.2f, third: %r' %('hi!', 3.14, 'bye!'))
print('this is a string with an {}' .format('insert'))
print('the {2} {1} {0}' .format('fox', 'brown', 'quick'))
print('first object: {a}, second object: {b}, third object: {c}' .format(a=1, b='two', c=12.3))
print('a %s saved is a %s earned.' %('penny', 'penny'))
print('a {p} saved is a {p} earned.' .format(p='penny'))
print('{0:8} | {1:9}' .format('fruit', 'quantity'))
print('{0:8} | {1:9}' .format('apples', 3.))
print('{0:8} | {1:9}' .format('oranges', 10))
print('{0:8} | {1:^8} | {2:>8}' .format('left', 'centre','right'))
print('{0:<8} | {1:^8} | {2:<8}' .format(11,22,33))
print('{0:=<8} | {1:-^8} | {2:.>8}' .format('left','centre','right'))
print('{0:=<8} | {1:-^8} | {2:.>8}' .format(11,22,33))
print('this is my ten-character, two-decimal number: %10.2f' %13.579)
print('this is my ten-character, two-decimal number:(0:10.2f)' .format(13.579))
name = 'fred'
print(f"he said his name is {name}.")
print(f"he said his name is {name!r}")
num = 23.45678
print("my 10 character, four decimal number is: {0:10.4f}" .format(num))
print(f"my 10 character, four decimal number is:{num:{10}.{6}}")

